# Generated by Django 2.1.4 on 2019-01-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE public.ads_company DISTRIBUTE BY HASH(id);"
        ),
    ]
