# Generated by Django 2.1.5 on 2019-01-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20190123_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SampleB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sample_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.SampleA')),
            ],
        ),
    ]
