# Generated by Django 2.1.5 on 2019-01-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_samplea_sampleb'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE public.ads_sampleb DISTRIBUTE BY HASH(id);"
        ),

    ]
